### ISSUE TITLE
Handling connectedCallback and disconnectedCallback

### ISSUE THREAD

**Issue by EisenbergEffect** [sheeshpaul/webcomponents-redux#1]
I had a read through the code. It's all pretty straight forward and makes good sense. However, the way that the connected/disconnected functionality is mixed in seems a bit odd, and also not accounting for a common scenario where many if not all web components will define those callbacks.

If the callback is present, could we instead wrap the original? Also, can we get away from leveraging __proto in the mixin implementations?

Other than those two issues, this looks pretty solid. Thanks for working on it!

**Comment by sheeshpaul** [comment]
Thanks for your feedback. As you suggested, I have wrapped connectedCallback and disconnectedCallback and there is no need to call connect/disconnect state functions, and also removed the proto. These changes have been published in version 2.0.0

**Comment by sheeshpaul** [comment]
Fixed in version 2.0.0

**Comment by EisenbergEffect** [comment]
Nice!
